spring:
  application:
    name: ApiGatewayApplication

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]": # Apply CORS for all routes
            allowedOrigins:
              - "http://localhost:8080" # Allow frontend domain (Change as needed)
              - "http://localhost:5173" # Allow another frontend domain (Change as needed)
              - "https://anupam-inventory.netlify.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true # Allow cookies and authorization headers

      routes:
        - id: PRODUCTCATEGORY
          uri: lb://PRODUCTCATEGORY
          predicates:
            - Path=/productcategory/**
          filters:
            - StripPrefix=1

        - id: SUPPLIERSTOCK
          uri: lb://SUPPLIERSTOCK
          predicates:
            - Path=/supplierstock/**
          filters:
            - StripPrefix=1
        - id: ORDERSALE
          uri: lb://ORDERSALE
          predicates:
            - Path=/ordersale/**
          filters:
            - StripPrefix=1
        - id: AUTHSERVER
          uri: lb://AUTHSERVER
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

server:
  port: ${SERVER_PORT:8888} # Default port for the API Gateway

eureka:
  instance:
    prefer-ip-address: true # Register with IP instead of hostname
    hostname: ${spring.cloud.client.ip-address} # Explicit IP
    instance-id: ${spring.application.name}:${server.port} # Unique instance ID
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/} # Eureka server URL
