spring:
  application:
    name: AuthServer

  data:
    redis:
      port: ${SPRING_REDIS_PORT:6380}
      host: ${SPRING_REDIS_HOST:localhost}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:lugun}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  instance:
    prefer-ip-address: true # Register with IP instead of hostname
    hostname: ${spring.cloud.client.ip-address} # Explicit IP
    instance-id: ${spring.application.name}:${server.port} # Unique instance ID
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/} # Eureka server URL

server:
  port: ${SERVER_PORT:8008}

jwt:
  secret: ${MY_SECRET_KEY:mySecretKeymySecretKeymySecretKeymySecretKey}
  access-expiration: ${JWT_ACCESS_EXPIRATION:300000} # 5 minutes
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

