name: CI/CD Microservices Build & Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # === API Gateway ===
      - name: Build API Gateway
        run: |
          cd ApiGatewayApplication
          mvn clean install
          DOCKER_TAG="api-gateway:${GITHUB_SHA}"
          docker build -t $DOCKER_TAG .
          docker tag $DOCKER_TAG ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG

      # === Auth Service ===
      - name: Build Auth Service
        run: |
          cd AuthServer
          mvn clean install
          DOCKER_TAG="auth-service:${GITHUB_SHA}"
          docker build -t $DOCKER_TAG .
          docker tag $DOCKER_TAG ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG

      # === Order Sale Service ===
      - name: Build Order Sale Service
        run: |
          cd OrderSale
          mvn clean install
          DOCKER_TAG="order-sale-service:${GITHUB_SHA}"
          docker build -t $DOCKER_TAG .
          docker tag $DOCKER_TAG ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG

      # === Supplier Stock Service ===
      - name: Build Supplier Stock Service
        run: |
          cd SupplierStock
          mvn clean install
          DOCKER_TAG="supplier-stock-service:${GITHUB_SHA}"
          docker build -t $DOCKER_TAG .
          docker tag $DOCKER_TAG ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG

      # === Product Category Service ===
      - name: Build Product Category Service
        run: |
          cd ProductCategory
          mvn clean install
          DOCKER_TAG="product-category-service:${GITHUB_SHA}"
          docker build -t $DOCKER_TAG .
          docker tag $DOCKER_TAG ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG

      # === Eureka Server ===
      - name: Build Eureka Server
        run: |
          cd servicediscovery
          mvn clean install
          DOCKER_TAG="eureka-server:${GITHUB_SHA}"
          docker build -t $DOCKER_TAG .
          docker tag $DOCKER_TAG ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_TAG
